version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: ${ECR_URL}/miraki_api:{CIRCLE_BUILD_NUM}
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "5000:5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ${ECR_URL}/miraki_postgres:{CIRCLE_BUILD_NUM}
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres


  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: ${ECR_URL}/miraki_celeryworker:{CIRCLE_BUILD_NUM}
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ${ECR_URL}/miraki_celerybeat:{CIRCLE_BUILD_NUM}
    command: /start-celerybeat

  flower:
    <<: *django
    image: ${ECR_URL}/miraki_flower:{CIRCLE_BUILD_NUM}
    command: /start-flower

