version: '2.1'

jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - slack/notify:
          channel: C05BV0S9JBC
          event: pass
          template: success_tagged_deploy_1
workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context:
            - slack-secrets