apiVersion: v1
kind: Secret
metadata:
  namespace: {EKS_NAMESPACE}
  name: secrets-{EKS_NAMESPACE}-postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: "KStxVuwLKu6wMsFUw5VE71FSGPsyUjHsuG0yfLMKT1Mj6w1k16Ntr1epVOrbb4OD"
