# Generated by Django 4.1.9 on 2023-06-12 14:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ControlModule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ControlSystem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
                (
                    "control_module",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.controlmodule"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
                ("area", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.area")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("number", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=300, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
                (
                    "control_system",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.controlsystem"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.CharField(blank=True, max_length=100, null=True)),
                ("longitude", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.userprofile"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customers.organization"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionSchedule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("number", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.userprofile"),
                ),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.order")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProcessData",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                (
                    "data_point",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.datapoint"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManufacturingFacility",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387223)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 12, 20, 10, 36, 387415))),
                ("alarm", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.alarm")),
                ("area", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.area")),
                (
                    "control_module",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.controlmodule"),
                ),
                (
                    "control_system",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.controlsystem"),
                ),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.userprofile"),
                ),
                (
                    "equipment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.equipment"),
                ),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.event")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.order")),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customers.organization"),
                ),
                (
                    "process_data",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.processdata"),
                ),
                (
                    "production_schedule",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.productionschedule"),
                ),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.site")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.unit")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="controlmodule",
            name="unit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.unit"),
        ),
        migrations.AddField(
            model_name="area",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.userprofile"),
        ),
        migrations.AddField(
            model_name="area",
            name="site",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub_tenant.site"),
        ),
    ]
