# Generated by Django 4.1.9 on 2023-06-26 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub_tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="agv",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92727)),
        ),
        migrations.AlterField(
            model_name="agv",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92793)),
        ),
        migrations.AlterField(
            model_name="area",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134938)),
        ),
        migrations.AlterField(
            model_name="area",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134980)),
        ),
        migrations.AlterField(
            model_name="cnc",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92727)),
        ),
        migrations.AlterField(
            model_name="cnc",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92793)),
        ),
        migrations.AlterField(
            model_name="connectioninfo",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92727)),
        ),
        migrations.AlterField(
            model_name="connectioninfo",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92793)),
        ),
        migrations.AlterField(
            model_name="edgedevice",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92727)),
        ),
        migrations.AlterField(
            model_name="edgedevice",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92793)),
        ),
        migrations.AlterField(
            model_name="line",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134938)),
        ),
        migrations.AlterField(
            model_name="line",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134980)),
        ),
        migrations.AlterField(
            model_name="machine",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134938)),
        ),
        migrations.AlterField(
            model_name="machine",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134980)),
        ),
        migrations.AlterField(
            model_name="plc",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92727)),
        ),
        migrations.AlterField(
            model_name="plc",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92793)),
        ),
        migrations.AlterField(
            model_name="process",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134938)),
        ),
        migrations.AlterField(
            model_name="process",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134980)),
        ),
        migrations.AlterField(
            model_name="robot",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92727)),
        ),
        migrations.AlterField(
            model_name="robot",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92793)),
        ),
        migrations.AlterField(
            model_name="site",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134938)),
        ),
        migrations.AlterField(
            model_name="site",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134980)),
        ),
        migrations.AlterField(
            model_name="tagtopics",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134938)),
        ),
        migrations.AlterField(
            model_name="tagtopics",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 134980)),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92727)),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92793)),
        ),
        migrations.AlterField(
            model_name="vision",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92727)),
        ),
        migrations.AlterField(
            model_name="vision",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 19, 46, 57, 92793)),
        ),
    ]
