# Generated by Django 4.1.9 on 2023-08-09 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub_tenant", "0009_alter_agv_created_at_alter_agv_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="line",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="process",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="site",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tagtopics",
            name="area_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tagtopics",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tagtopics",
            name="line_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tagtopics",
            name="machine_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tagtopics",
            name="site_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agv",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="agv",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
        migrations.AlterField(
            model_name="area",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954021)),
        ),
        migrations.AlterField(
            model_name="area",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954049)),
        ),
        migrations.AlterField(
            model_name="cnc",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="cnc",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
        migrations.AlterField(
            model_name="connectioninfo",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="connectioninfo",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
        migrations.AlterField(
            model_name="edgedevice",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="edgedevice",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
        migrations.AlterField(
            model_name="line",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954021)),
        ),
        migrations.AlterField(
            model_name="line",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954049)),
        ),
        migrations.AlterField(
            model_name="machine",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954021)),
        ),
        migrations.AlterField(
            model_name="machine",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="machine",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954049)),
        ),
        migrations.AlterField(
            model_name="mydashboard",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="mydashboard",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
        migrations.AlterField(
            model_name="plc",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="plc",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
        migrations.AlterField(
            model_name="process",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954021)),
        ),
        migrations.AlterField(
            model_name="process",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954049)),
        ),
        migrations.AlterField(
            model_name="robot",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="robot",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
        migrations.AlterField(
            model_name="site",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954021)),
        ),
        migrations.AlterField(
            model_name="site",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954049)),
        ),
        migrations.AlterField(
            model_name="tagtopics",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954021)),
        ),
        migrations.AlterField(
            model_name="tagtopics",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 954049)),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
        migrations.AlterField(
            model_name="vision",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915354)),
        ),
        migrations.AlterField(
            model_name="vision",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 16, 12, 915386)),
        ),
    ]
