apiVersion: v1
kind: ConfigMap
metadata:
  namespace: miraki-production
  name: envs-miraki-production-django
data:
  DJANGO_SETTINGS_MODULE: "config.settings.miraki-production"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECURE_SSL_REDIRECT: "no"
  DJANGO_ACCOUNT_ALLOW_REGISTRATION: "no"
  WEB_CONCURRENCY: "4"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_FLOWER_USER: MUBdGcaHRYSqgMnTpxLEACvSMfJtfKbY
  CELERY_FLOWER_PASSWORD: 1BOiljkqeqbiQzS209FrOX6ogTVRNb25sUtxbSUjg4qJZ9jnyX2GApGQQQo3YoTS

  DJANGO_SECRET_KEY: nJW9UShw5pyxLB152mLxBOjDokGW92t3tBVI5nTOllgjlbnaVa4iMKpxtGQnAV3h
  DJANGO_ADMIN_URL: "1Mxkaqc3FfDaaiipCBtZxjGnVJQC9MzX/"
  DJANGO_AWS_ACCESS_KEY_ID: AKIATO76J2JT2D4VVSO7
  DJANGO_AWS_SECRET_ACCESS_KEY: 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
  DJANGO_AWS_STORAGE_BUCKET_NAME: miraki-miraki
  MENTO_FRONTEND_URL: http://mento.miraki.ai
  # # Email
  # # ------------------------------------------------------------------------------
  # DJANGO_SERVER_EMAIL: 


  # # AWS
  # # ------------------------------------------------------------------------------

  # # django-allauth
  # # ------------------------------------------------------------------------------
  # DJANGO_ACCOUNT_ALLOW_REGISTRATION: True



