apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prod
  name: envs-prod-django
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DJANGO_SECURE_SSL_REDIRECT: "no"
  DJANGO_ACCOUNT_ALLOW_REGISTRATION: "yes"
  WEB_CONCURRENCY: "4"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_FLOWER_USER: MUBdGcaHRYSqgMnTpxLEACvSMfJtfKbY
  CELERY_FLOWER_PASSWORD: 1BOiljkqeqbiQzS209FrOX6ogTVRNb25sUtxbSUjg4qJZ9jnyX2GApGQQQo3YoTS

  DJANGO_SECRET_KEY: nJW9UShw5pyxLB152mLxBOjDokGW92t3tBVI5nTOllgjlbnaVa4iMKpxtGQnAV3h
  DJANGO_ADMIN_URL: "1Mxkaqc3FfDaaiipCBtZxjGnVJQC9MzX/"
  DJANGO_AWS_ACCESS_KEY_ID: AKIATO76J2JT2D4VVSO7
  DJANGO_AWS_SECRET_ACCESS_KEY: 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
  DJANGO_AWS_STORAGE_BUCKET_NAME: miraki-lexus
  DJANGO_AWS_S3_REGION_NAME: ap-south-1
  SENTRY_DSN: ""
  DJANGO_SERVER_EMAIL: ""
  GODADDY_API_KEY: e5NFDRKrCwjN_RxQYrgc8wBxyUStV6yh77M
  GODADDY_API_SECRET: BSfRu1fx6ATJ8AJycJvCc9
  ELB_URL: k8s-prod-ingress-2607fb3d8d-588934041.ap-south-1.elb.amazonaws.com
  GODADDY_DOMAIN: miraki.ai
  AWS_SES_REGION_ENDPOINT: email-smtp.ap-south-1.amazonaws.com
  AWS_SES_ACCESS_KEY_ID: AKIATO76J2JT2X2HT25X
  AWS_SES_SECRET_ACCESS_KEY: BIVcBqrG2G3QIQZFrIwmq3X0EYSTzRDqdFY6qoOLmNo1
  EMAIL_HOST: email-smtp.ap-south-1.amazonaws.com
  EMAIL_PORT: "587"

  # # Email
  # # ------------------------------------------------------------------------------
  # DJANGO_SERVER_EMAIL: 


  # # AWS
  # # ------------------------------------------------------------------------------

  # # django-allauth
  # # ------------------------------------------------------------------------------



