apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume-production-v-1-0-0
  namespace: prod
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/production/v_1_0_0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-claim-production-v-1-0-0
  namespace: prod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi