apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume-miraki-production
  namespace: miraki-production
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-claim-miraki-production
  namespace: miraki-production
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi