apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume-production
  namespace: prod
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/production

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-claim-production
  namespace: prod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi