apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: celeryworker
  namespace: {EKS_NAMESPACE}
  name: celeryworker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: celeryworker
  template:
    metadata:
      labels:
        service: celeryworker
    spec:
      containers:
      - name: celeryworker
        image: 238367134311.dkr.ecr.ap-south-1.amazonaws.com/miraki/miraki_celeryworker:{IMAGE_TAG}
        args:
          - /start-celeryworker
        envFrom:
          - configMapRef:
              name: envs-{EKS_NAMESPACE}-django
          - configMapRef:
              name: envs-{EKS_NAMESPACE}-postgres
          - secretRef:
              name: secrets-{EKS_NAMESPACE}-django
          - secretRef:
              name: secrets-{EKS_NAMESPACE}-postgres
        env:
          - name: CELERY_BROKER_URL
            value: $(REDIS_URL)
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      restartPolicy: Always