apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: celerybeat
  namespace: {EKS_NAMESPACE}
  name: celerybeat
spec:
  replicas: 1
  selector:
    matchLabels:
      service: celerybeat
  template:
    metadata:
      labels:
        service: celerybeat
    spec:
      containers:
      - args:
        - /start-celerybeat
        envFrom:
        - configMapRef:
            name: envs-{EKS_NAMESPACE}-django
        - configMapRef:
            name: envs-{EKS_NAMESPACE}-postgres
        - secretRef:
            name: secrets-{EKS_NAMESPACE}-django
        - secretRef:
            name: secrets-{EKS_NAMESPACE}-postgres
        image: 238367134311.dkr.ecr.ap-south-1.amazonaws.com/miraki/miraki_celerybeat:{IMAGE_TAG}
        name: celerybeat
      restartPolicy: Always