apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: celeryworker
  namespace: prod
  name: celeryworker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: celeryworker
  template:
    metadata:
      labels:
        service: celeryworker
    spec:
      containers:
      - name: celeryworker
        image: 238367134311.dkr.ecr.ap-south-1.amazonaws.com/miraki/miraki_celeryworker:{CIRCLE_BUILD_NUM}
        args:
          - /start-celeryworker
        envFrom:
          - configMapRef:
              name: envs-prod-django
          - configMapRef:
              name: envs-prod-postgres
          - secretRef:
              name: secrets-prod-django
          - secretRef:
              name: secrets-prod-postgres
        env:
          - name: CELERY_BROKER_URL
            value: $(REDIS_URL)
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      restartPolicy: Always