apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: celeryflower
  namespace: {EKS_NAMESPACE}
  name: celeryflower  # name should be anything put flower: https://github.com/mher/flower/issues/738
spec:
  replicas: 1
  selector:
    matchLabels:
      service: celeryflower
  template:
    metadata:
      labels:
        service: celeryflower
    spec:
      containers:
      - args:
        - /start-flower
        envFrom:
          - configMapRef:
              name: envs-{EKS_NAMESPACE}-django
          - configMapRef:
              name: envs-{EKS_NAMESPACE}-postgres
          - secretRef:
              name: secrets-{EKS_NAMESPACE}-django
          - secretRef:
              name: secrets-{EKS_NAMESPACE}-postgres
        image: 238367134311.dkr.ecr.ap-south-1.amazonaws.com/miraki/miraki_flower:{IMAGE_TAG}
        name: celeryflower
        ports:
          - containerPort: 5555
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  name: celeryflower
  namespace: {EKS_NAMESPACE}
  labels:
    service: celeryflower
spec:
  ports:
  - port: 5555
    targetPort: 5555
    name: http
  selector:
    service: celeryflower
