apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgres
  namespace: {EKS_NAMESPACE}
  name: postgres
spec:
  selector:
    matchLabels:
      service: postgres
  serviceName: "postgres"
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: envs-{EKS_NAMESPACE}-postgres
          - secretRef:
              name: secrets-{EKS_NAMESPACE}-postgres
        image: 238367134311.dkr.ecr.ap-south-1.amazonaws.com/miraki/miraki_postgres:{IMAGE_TAG}
        name: postgres
        ports:
          - containerPort: 5432
            name: postgredb
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: postgres-pvc-claim-production-{EKS_NAMESPACE}-v-1-0-0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgres
  namespace: {EKS_NAMESPACE}
  name: postgres
spec:
  ports:
  - name: "5432"
    port: 5432
  selector:
    service: postgres
status:
  loadBalancer: {}
