# Generated by Django 4.1.9 on 2023-06-15 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Licence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 15, 19, 58, 48, 356424)),
                ),
                ("updated_at", models.DateTimeField(default=datetime.datetime(2023, 6, 15, 19, 58, 48, 356462))),
                ("name", models.CharField(max_length=100)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("is_trial", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("sites_allowed", models.IntegerField(default=0)),
                ("areas_allowed", models.IntegerField(default=0)),
                ("lines_allowed", models.IntegerField(default=0)),
                ("tags_allowed", models.IntegerField(default=0)),
                ("users_allowed", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="license",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="customers.licence"
            ),
        ),
    ]
